version: '3.9'
services:
  my-app:
    image: ak-trading-and-logging
    ports:
      - "${PORT}:80"
    env_file: .env.local

  db:
    mysql:
      image: mysql
      container_name: ${DB_NAME}
      restart: always
      ports:
        - "${DB_PORT}:3306"
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      env_file: .env.local
      # volumes:

  cache:
    redis:
      image: redis
      restart: always
      ports:
        - "${REDIS_PORT}:6379"
      env_file: .env.local