version: '1'
services:
  my-app:
    image: ak-trading-and-logging
    env_file:
      - .env.local
    ports:
      -3001:3001
  db:
    mysql:
      image: mysql
      restart: always
      env_file:
        - .env.local
      ports:
        -"3306:3306"
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        # -
  cache:
    redis:
      image: redis
      restart: always
      env_file:
        - .env.local
      ports:
