version: '1'
services:
  my-app:
    image: ak-trading-and-logging
    env_file:
      - .env.prod
    ports:
      -3001:3001
  # mysql:
  #   image: mysql
  #   env_file:
  #     - .env
  #   ports:
  #     -"3306:3306"
  #   volumes:
      # -