POST https://apiconnect.angelbroking.com/rest/auth/angelbroking/user/v1/loginByPassword
content-type: application/json
Accept: application/json
X-UserType: USER
X-SourceID: WEB
X-ClientLocalIP: CLIENT_LOCAL_IP
X-ClientPublicIP: CLIENT_PUBLIC_IP
X-MACAddress: MAC_ADDRESS
X-PrivateKey: API_KEY
Authorization:

{
    "name": "sample",
    "time": "Wed 21 Oct 2015 18:27:50 GMT"
}

####
GET {{$dotenv ANGEL_BASE_URL}}/portfolio/v1/getHolding
Authorization: ${{$dotenv .ANGEL_ACCESS_TOKEN}}
X-ClientLocalIP: ${{$dotenv .PRIVATE_IP}}
X-ClientPublicIP: ${{$dotenv .PUBLIC_IP}}
X-MACAddress: ${{$dotenv .MAC_ADDRESS}}
X-PrivateKey: ${{$dotenv .ANGEL_API_KEY}}

###
GET 